spring.jackson.serialization.write_dates_as_timestamps=false
spring.jackson.serialization.indent_output=true

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.jdbcUrl=jdbc:mysql://127.0.0.1:3306/okkio
spring.datasource.username=root
spring.datasource.password=Frequency@123

server.port=8092

application.projectVersion=@project.version@
application.corsExposedHeaders=X-Total-Count,X-App-Error

application.email=okkio.test@gmail.com
application.password=adtdtirtunhkylll

application.expiresIn=840000
application.secret=aitdokkio!@#
#12 Hours
application.refreshTokenDurationMs=43200000

application.redisHost=localhost
application.redisPort=6379
mybatis.type-aliases-package=io.okkio.domain
mybatis.mapper-locations=classpath:mybatis/*.xml

tastingNotes={\"AROMA\": \"PINEAPPLE\",\"ACIDITY\": \"APPLE\",\"BODY\": \"DARK CHOCOLATE\",\"FINISH\": \"HINT OR RIPE FRUIT AFTERTASTE\"}
readyToDrink=Cold Brew (general information): Coffee steeped with Toddy, for smooth quality, low acidity and bitterness but still full of flavor, light, faintly fruity. The use of Cold Brew with milk, tonic, or carbonated beverage is refreshing, diverse in ways of enjoying as it is really convenient in life.
shippingDelivery=[{\"id\":1,\"name\":\"Free Shipping Nationwide\",\"description\":\"For all orders over 300,000 VND\"},{\"id\":2,\"name\":\"Free return 30 days\",\"description\":\"Support payment when receiving goods, or pay via Visa/Master card and e-wallet\"},{\"id\":3,\"name\":\"Do you need support?\",\"description\":\"Call 1900 6931All days of the week (from 8:00 to 21:00)\"}]

contact.title=LET'S TALK ABOUT YOUR ORDER!
contact.address=Ho Chi Minh City
contact.phone=0869 356 116
contact.email=customer.support@okkiocaffe.com
contact.facebook=https://www.facebook.com/okkiocaffe
contact.instagram=https://www.instagram.com/okkiocaffe

order.description=Thank you for ordering at OKKIO . Within the next 24 hours, OKKIO staff will call to confirm and deliver this order. If you need any advice, please call the hotline.

path.image=images
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB