spring.jackson.serialization.write_dates_as_timestamps=false
spring.jackson.serialization.indent_output=true

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.jdbcUrl=jdbc:mysql://127.0.0.1:3306/okkio
spring.datasource.username=root
spring.datasource.password=Frequency@123

server.port=8092

application.projectVersion=@project.version@
application.corsExposedHeaders=X-Total-Count,X-App-Error

application.expiresIn=840000
application.secret=aitdokkio!@#
#15Minute
application.refreshTokenDurationMs=900000

application.redisHost=localhost
application.redisPort=6379
mybatis.type-aliases-package=io.okkio.domain
mybatis.mapper-locations=classpath:mybatis/*.xml